## DRAGON REAL ESTATE - PRICE PREDICTOR

In [1]:
import pandas as pd

In [2]:
housing = pd.read_csv("data.csv")

In [3]:
housing.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PIRATIO  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        B  LSTAT  MEDV  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [4]:
housing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 504 entries, 0 to 503
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   CRIM     504 non-null    float64
 1   ZN       504 non-null    float64
 2   INDUS    504 non-null    float64
 3   CHAS     504 non-null    int64  
 4   NOX      504 non-null    float64
 5   RM       504 non-null    float64
 6   AGE      504 non-null    float64
 7   DIS      504 non-null    float64
 8   RAD      504 non-null    int64  
 9   TAX      504 non-null    int64  
 10  PIRATIO  504 non-null    float64
 11  B        504 non-null    float64
 12  LSTAT    504 non-null    float64
 13  MEDV     504 non-null    float64
dtypes: float64(11), int64(3)
memory usage: 55.3 KB


In [5]:
housing['CHAS'].value_counts()

CHAS
0    469
1     35
Name: count, dtype: int64

In [6]:
housing.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  504.000000  504.000000  504.000000  504.000000  504.000000  504.000000   
mean     3.627551   11.408730   11.133631    0.069444    0.554622    6.284129   
std      8.615734   23.357742    6.873796    0.254461    0.116102    0.703554   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082155    0.000000    5.175000    0.000000    0.449000    5.884750   
50%      0.260420    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.681942   12.500000   18.100000    0.000000    0.624000    6.620500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PIRATIO           B  \
count  504.000000  504.000000  504.000000  504.000000  504.000000  504.000000   
mean    68.509524    3.800392    9.583333  408.773810   18.445437  356.521250   
std     28.184279    2.108169    8.707815  168.655543    2.163280   91.443771   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     44.850000    2.097050    4.000000  279.750000   17.375000  375.300000   
50%     77.150000    3.215700    5.000000  330.000000   19.000000  391.385000   
75%     94.100000    5.212575   24.000000  666.000000   20.200000  396.215000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT       MEDV  
count  504.000000  504.00000  
mean    12.674782   22.55496  
std      7.146747    9.20311  
min      1.730000    5.00000  
25%      6.990000   17.07500  
50%     11.395000   21.20000  
75%     16.992500   25.00000  
max     37.970000   50.00000

In [7]:
%matplotlib inline


In [8]:
#import matplotlib.pyplot as plt
#housing.hist(bins=50, figsize=(20,15))


## Train-Test Splitting

In [9]:
#for learning purpose
import numpy as np
def split_train_test(data, test_ratio):
    np.random.seed(42)
    shuffled = np.random.permutation(len(data))
    test_set_size = int(len(data) * test_ratio)
    test_indices = shuffled[:test_set_size]
    train_indices = shuffled[test_set_size:]
    return data.iloc[train_indices],data.iloc[test_indices]

In [10]:
#train_set,test_set = split_train_test(housing, 0.2)

In [11]:
#print(f"Rows in train set: {len(train_set)}\nRows in test set: {len(test_set)}\n")

In [12]:
from sklearn.model_selection import train_test_split
train_set, test_set = train_test_split(housing, test_size=0.2, random_state=42)
print(f"Rows in train set: {len(train_set)}\nRows in test set: {len(test_set)}\n")

Rows in train set: 403
Rows in test set: 101



In [13]:
from sklearn.model_selection import StratifiedShuffleSplit
split = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
for train_index, test_index in split.split(housing, housing['CHAS']):
    strat_train_set = housing.loc[train_index]
    strat_test_set = housing.loc[test_index]

In [14]:
strat_test_set['CHAS'].value_counts()

CHAS
0    94
1     7
Name: count, dtype: int64

In [15]:
strat_train_set['CHAS'].value_counts()

CHAS
0    375
1     28
Name: count, dtype: int64

In [16]:
#28/7

In [17]:
#375/94

In [18]:
housing = strat_train_set.copy()

## Looking for correlations

In [19]:
corr_matrix = housing.corr()
corr_matrix['MEDV'].sort_values(ascending=False)

MEDV       1.000000
RM         0.688941
B          0.365352
ZN         0.347170
DIS        0.254965
CHAS       0.209292
AGE       -0.379051
RAD       -0.390893
CRIM      -0.403558
NOX       -0.432385
TAX       -0.477117
INDUS     -0.491494
PIRATIO   -0.507178
LSTAT     -0.747563
Name: MEDV, dtype: float64

In [20]:
#from pandas.plotting import scatter_matrix
#attributes = ["MEDV", "RM" , "ZN" , "LSTAT"]
#scatter_matrix(housing[attributes], figsize= (12,8))

In [21]:
#housing.plot(kind="scatter", x="RM", y="MEDV", alpha=0.8)

# Trying out attributes combination

In [22]:
housing["TAXRM"]=housing["TAX"]/housing["RM"]

In [23]:
housing["TAXRM"]

481     98.666667
96      44.783385
301     49.924127
189     55.393180
140     70.780693
          ...    
163     48.119403
423    109.126659
98      35.294118
455    102.068966
154     65.752978
Name: TAXRM, Length: 403, dtype: float64

In [24]:
housing.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  \
481  5.70818   0.0  18.10     0  0.532  6.750  74.9  3.3317   24  666   
96   0.11504   0.0   2.89     0  0.445  6.163  69.6  3.4952    2  276   
301  0.03537  34.0   6.09     0  0.433  6.590  40.4  5.4917    7  329   
189  0.08370  45.0   3.44     0  0.437  7.185  38.9  4.5667    5  398   
140  0.29090   0.0  21.89     0  0.624  6.174  93.6  1.6119    4  437   

     PIRATIO       B  LSTAT  MEDV      TAXRM  
481     20.2  393.07   7.74  23.7  98.666667  
96      18.0  391.83  11.34  21.4  44.783385  
301     16.1  395.75   9.50  22.0  49.924127  
189     15.2  396.90   5.39  34.9  55.393180  
140     21.2  388.08  24.16  14.0  70.780693

In [25]:
corr_matrix = housing.corr()
corr_matrix['MEDV'].sort_values(ascending=False)

MEDV       1.000000
RM         0.688941
B          0.365352
ZN         0.347170
DIS        0.254965
CHAS       0.209292
AGE       -0.379051
RAD       -0.390893
CRIM      -0.403558
NOX       -0.432385
TAX       -0.477117
INDUS     -0.491494
PIRATIO   -0.507178
TAXRM     -0.544489
LSTAT     -0.747563
Name: MEDV, dtype: float64

In [26]:
#housing.plot(kind="scatter", x="TAXRM", y="MEDV", alpha=0.8)

In [27]:
housing = strat_train_set.drop("MEDV", axis=1)
housing_labels = strat_train_set["MEDV"].copy()

In [28]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer( strategy = "median")
imputer.fit(housing)


SimpleImputer(strategy='median')

In [29]:
imputer.statistics_

array([2.8392e-01, 0.0000e+00, 9.9000e+00, 0.0000e+00, 5.3800e-01,
       6.2080e+00, 7.7300e+01, 3.1523e+00, 5.0000e+00, 3.3700e+02,
       1.9000e+01, 3.9094e+02, 1.1500e+01])

In [30]:
X = imputer.transform(housing)

In [31]:
housing_tr = pd.DataFrame(X, columns=housing.columns)

In [32]:
housing_tr.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  403.000000  403.000000  403.000000  403.000000  403.000000  403.000000   
mean     3.590529   10.863524   11.343499    0.069479    0.557781    6.276521   
std      8.092174   22.171566    6.886304    0.254583    0.116968    0.712196   
min      0.006320    0.000000    0.740000    0.000000    0.389000    3.561000   
25%      0.086855    0.000000    5.190000    0.000000    0.453000    5.878500   
50%      0.283920    0.000000    9.900000    0.000000    0.538000    6.208000   
75%      3.766895   12.500000   18.100000    0.000000    0.627500    6.629500   
max     73.534100  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PIRATIO           B  \
count  403.000000  403.000000  403.000000  403.000000  403.000000  403.000000   
mean    68.690819    3.754655    9.756824  412.687345   18.466998  353.214069   
std     28.316177    2.096504    8.731223  168.738874    2.128152   96.157949   
min      2.900000    1.129600    1.000000  187.000000   13.000000    0.320000   
25%     44.050000    2.049300    4.000000  284.000000   17.400000  374.555000   
50%     77.300000    3.152300    5.000000  337.000000   19.000000  390.940000   
75%     94.100000    5.100400   24.000000  666.000000   20.200000  395.630000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT  
count  403.000000  
mean    12.824640  
std      7.242768  
min      1.730000  
25%      6.910000  
50%     11.500000  
75%     17.115000  
max     36.980000

In [33]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
my_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy = "median")),
    ('std_scaler', StandardScaler()),
])

In [34]:
housing_num_tr = my_pipeline.fit_transform(housing)

In [35]:
housing_num_tr.shape

(403, 13)

## Selecting a desired model for dragon real estate

In [36]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
#model = LinearRegression()
#model = DecisionTreeRegressor()
model = RandomForestRegressor()
model.fit(housing_num_tr, housing_labels)

RandomForestRegressor()

In [37]:
some_data = housing.iloc[:5]

In [38]:
some_labels = housing_labels.iloc[:5]

In [39]:
prepared_data = my_pipeline.transform(some_data)

In [40]:
model.predict(prepared_data)

array([25.763, 21.916, 23.709, 34.962, 14.396])

In [41]:
list(some_labels)

[23.7, 21.4, 22.0, 34.9, 14.0]

# Evaluating the model

In [42]:
from sklearn.metrics import mean_squared_error
housing_predictions = model.predict(housing_num_tr)
mse = mean_squared_error(housing_labels, housing_predictions)
rmse = np.sqrt(mse)

In [43]:
rmse

1.2670603147408037

In [44]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(model, housing_num_tr, housing_labels, scoring="neg_mean_squared_error", cv=10)
rmse_scores = np.sqrt(-scores)

In [45]:
rmse_scores

array([3.11231429, 2.89162177, 4.25201663, 2.99038457, 3.05380128,
       2.8515463 , 3.69269961, 2.84926642, 3.3951499 , 4.92856494])

In [46]:
def print_scores(scores):
    print("scores:", scores)
    print("Mean: ", scores.mean())
    print("Standard deviation: ",scores.std())

In [47]:
print_scores(rmse_scores)

scores: [3.11231429 2.89162177 4.25201663 2.99038457 3.05380128 2.8515463
 3.69269961 2.84926642 3.3951499  4.92856494]
Mean:  3.4017365703561153
Standard deviation:  0.6618963896237353


In [48]:
from joblib import dump, load
dump(model, 'Dragon.joblib')

['Dragon.joblib']

In [49]:
X_test = strat_test_set.drop("MEDV", axis=1)
Y_test = strat_test_set["MEDV"].copy()
X_test_prepared = my_pipeline.transform(X_test)
final_predictions = model.predict(X_test_prepared)
final_mse = mean_squared_error(Y_test, final_predictions)
final_rmse = np.sqrt(final_mse)
final_predictions

In [50]:
final_rmse

3.0622996551966994

In [52]:
prepared_data[0]

array([ 0.26201646, -0.49058452,  0.98237018, -0.27325202, -0.22068342,
        0.66564166,  0.21955292, -0.20199385,  1.63331998,  1.50307703,
        0.81533477,  0.4149992 , -0.70290259])